name: Build-Elite

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install ldid
        run: brew install ldid

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos

      - name: Tải iOS SDK (Bắt buộc để không lỗi)
        run: |
          # Tải SDK 14.5 để tương thích tốt với iPhone 6s Plus
          git clone --depth 1 https://github.com/theos/sdks.git ~/theos/sdks

      - name: Build Package
        run: |
          export THEOS=~/theos
          export PATH=$THEOS/bin:$PATH
          # Thêm dòng này để chỉ định SDK vừa tải
          make package FINALPACKAGE=1
        env:
          THEOS: ~/theos

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Elite-Result-v4.8
          path: packages/*.deb
